### ISSUE TITLE
graph crashes editor (executed before being compiled)

### ISSUE THREAD

**Issue by slapin** [Zylann/godot_voxel#216]
Hi, I get crashes when graph is complicated enough (like 20 nodes), especially when I use Remap and Clamp nodes.
```
#0  0x0000000000beb632 in ArraySlice<float>::operator[] (this=0x7fffffffd620, i=0) at /home/slapin/godot-projects/small-game/src/modules/voxel/generators/graph/../../streams/../storage/../util/array_slice.h:47
#1  ArraySlice<float>::operator[] (i=<optimized out>, this=<optimized out>) at /home/slapin/godot-projects/small-game/src/modules/voxel/generators/graph/../../streams/../storage/../util/array_slice.h:47
#2  VoxelGraphRuntime::generate_single (this=this@entry=0x1e9cb870, position=...) at /home/slapin/godot-projects/small-game/src/modules/voxel/generators/graph/voxel_graph_runtime.cpp:582
#3  0x0000000000bd2e4f in VoxelGeneratorGraph::generate_single (this=0x1e9cb690, position=...) at /home/slapin/godot-projects/small-game/src/modules/voxel/generators/graph/voxel_generator_graph.cpp:336
#4  0x0000000000e5474e in VoxelGraphEditor::update_previews (this=<optimized out>)
    at /home/slapin/godot-projects/small-game/src/modules/voxel/editor/graph/../../generators/graph/../../streams/../math/vector3i.h:33
#5  0x0000000000e5b31b in VoxelGraphEditor::_process (delta=<optimized out>, this=0x108f73c0) at /home/slapin/godot-projects/small-game/src/modules/voxel/editor/graph/voxel_graph_editor.cpp:153
#6  VoxelGraphEditor::_notification (p_what=25, this=0x108f73c0) at /home/slapin/godot-projects/small-game/src/modules/voxel/editor/graph/voxel_graph_editor.cpp:140
#7  VoxelGraphEditor::_notification (p_what=25, this=0x108f73c0) at /home/slapin/godot-projects/small-game/src/modules/voxel/editor/graph/voxel_graph_editor.cpp:137
#8  VoxelGraphEditor::_notificationv (this=0x108f73c0, p_notification=25, p_reversed=<optimized out>) at /home/slapin/godot-projects/small-game/src/modules/voxel/editor/graph/voxel_graph_editor.h:12
#9  0x0000000002b7de84 in Object::notification (this=0x108f73c0, p_notification=25, p_reversed=<optimized out>) at core/object.cpp:929
#10 0x0000000001ce49ea in SceneTree::_notify_group_pause (this=<optimized out>, p_group=..., p_notification=<optimized out>) at scene/main/scene_tree.cpp:985
#11 0x0000000001ceeb39 in SceneTree::idle (this=0xabc4580, p_time=0.0166666675) at scene/main/scene_tree.cpp:524
#12 0x0000000000797b8a in Main::iteration () at main/main.cpp:2103
#13 0x000000000077eea1 in OS_X11::run (this=this@entry=0x7fffffffda30) at platform/x11/os_x11.cpp:3607
#14 0x000000000076b283 in main (argc=3, argv=0x7fffffffe288) at platform/x11/godot_x11.cpp:56
(gdb) frame 4
#4  0x0000000000e5474e in VoxelGraphEditor::update_previews (this=<optimized out>)
    at /home/slapin/godot-projects/small-game/src/modules/voxel/editor/graph/../../generators/graph/../../streams/../math/vector3i.h:33
33		_FORCE_INLINE_ Vector3i(int px, int py, int pz) :
(gdb) list
28		explicit _FORCE_INLINE_ Vector3i(int xyz) :
29				x(xyz),
30				y(xyz),
31				z(xyz) {}
32	
33		_FORCE_INLINE_ Vector3i(int px, int py, int pz) :
34				x(px),
35				y(py),
36				z(pz) {}
37	
(gdb) frame 3
#3  0x0000000000bd2e4f in VoxelGeneratorGraph::generate_single (this=0x1e9cb690, position=...) at /home/slapin/godot-projects/small-game/src/modules/voxel/generators/graph/voxel_generator_graph.cpp:336
336		return _runtime.generate_single(position) * _iso_scale;
(gdb) list
331			default:
332				CRASH_NOW();
333				break;
334		}
335	
336		return _runtime.generate_single(position) * _iso_scale;
337	}
338	
339	Interval VoxelGeneratorGraph::analyze_range(Vector3i min_pos, Vector3i max_pos) {
340		return _runtime.analyze_range(min_pos, max_pos) * _iso_scale;
(gdb) frame 2
#2  VoxelGraphRuntime::generate_single (this=this@entry=0x1e9cb870, position=...) at /home/slapin/godot-projects/small-game/src/modules/voxel/generators/graph/voxel_graph_runtime.cpp:582
582		memory[0] = position.x;
(gdb) list
577	#ifdef TOOLS_ENABLED
578		ERR_FAIL_COND_V_MSG(!has_output(), 0.0, "The graph has no SDF output");
579	#endif
580	
581		ArraySlice<float> memory(_memory, 0, _memory.size() / 2);
582		memory[0] = position.x;
583		memory[1] = position.y;
584		memory[2] = position.z;
585	
586		uint32_t pc;
(gdb) frame 1
#1  ArraySlice<float>::operator[] (i=<optimized out>, this=<optimized out>) at /home/slapin/godot-projects/small-game/src/modules/voxel/generators/graph/../../streams/../storage/../util/array_slice.h:47
47		inline T &operator[](size_t i) {
(gdb) list
42			CRASH_COND(size_in_bytes % sizeof(U) != 0);
43	#endif
44			return ArraySlice<U>((U *)_ptr, 0, size_in_bytes / sizeof(U));
45		}
46	
47		inline T &operator[](size_t i) {
48	#ifdef DEBUG_ENABLED
49			CRASH_COND(i >= _size);
50	#endif
51			return _ptr[i];
(gdb) quit
```
Did not unnderstand what is going on, looks like input/output count is wrong somewhere.

**Comment by Zylann** [comment]
According to your call stack the crash seems to happen right at the begin of the execution (before any node runs), so it might not be related to the number of nodes, but rather a series of actions that causes an invalid state.

> voxel_graph_runtime.cpp:582

This corresponds to that line:
```
#ifdef DEBUG_ENABLED
	CRASH_COND(_memory.size() == 0);
#endif
#ifdef TOOLS_ENABLED
	ERR_FAIL_COND_V_MSG(!has_output(), 0.0, "The graph has no SDF output");
#endif

	ArraySlice<float> memory(_memory, 0, _memory.size() / 2);
	memory[0] = position.x; <-------------
```

It means the graph got executed before getting compiled.

Do you have a reproduction case for this?

**Comment by slapin** [comment]
I just did noise heightmap and added remap and clam pto it, will post
screenshot soon

**Comment by Zylann** [comment]
Does this still happen? I haven't got such a crash in a long time.

**Comment by Zylann** [comment]
Closing, if it happens again you can reopen with a repro

**Comment by slapin** [comment]
Hi, will be able to check the following weekend.

вс, 10 июл. 2022 г., 19:56 Marc ***@***.***>:
