### ISSUE TITLE
`debug_print_sdf_top_down` increase memory usage each time when it is called

### ISSUE THREAD

**Issue by qarmin** [Zylann/godot_voxel#330]
Fixing this, probably will fix CI fuzzer crashes

Code to reproduce
```
extends Node
# Called when the node enters the scene tree for the first time.
func _process(delta):
	for i in get_children():
		i.queue_free()

######################################## VoxelLodTerrain ########################################
	var temp_variable1 = VoxelLodTerrain.new()
	add_child(temp_variable1)
	temp_variable1.debug_print_sdf_top_down(Vector3(randi()%100,randi()%100,randi()%100),Vector3(randi()%100,randi()%100,randi()%100))
	temp_variable1.debug_print_sdf_top_down(Vector3(randi()%100,randi()%100,randi()%100),Vector3(randi()%100,randi()%100,randi()%100))
	temp_variable1.debug_print_sdf_top_down(Vector3(randi()%100,randi()%100,randi()%100),Vector3(randi()%100,randi()%100,randi()%100))
	
	print("MEM_DYNAMIC: " + str(Performance.get_monitor(Performance.MEMORY_DYNAMIC)/(1024*1024)) + " MB")
	print("MEM_STATIC: " + str(Performance.get_monitor(Performance.MEMORY_STATIC)/(1024*1024)) + " MB")
	print("MEM_DYNAMIC_MAX: " + str(Performance.get_monitor(Performance.MEMORY_DYNAMIC_MAX)/(1024*1024)) + " MB")
	print("MEM_STATIC_MAX: " + str(Performance.get_monitor(Performance.MEMORY_STATIC_MAX)/(1024*1024)) + " MB")
```
Meory will slowly increase from 300 MB to even 2,5GB after few minutes

**Comment by Zylann** [comment]
The reason it happens is because voxel data uses a memory pool. This pool is quite naive at the moment: it assumes most of the time, VoxelBuffer data will have the same sizes. That tends to be true because all chunks and temporary buffers have common sizes, and the rare times a VoxelBuffer is needed with arbitrary size are not often.

When a VoxelBuffer is given a size that was never used before, a new pool is created for blocks of that size. But if you keep using different sizes everytime, it will behave pretty much like a memory leak because none of these allocations will really get re-used...

**Comment by qarmin** [comment]
Looks that `debug_print_sdf_top_down` is the only function that increase memory in this way, so in https://github.com/Zylann/godot_voxel/pull/331 I just disabled it.

Looks that also `VoxelTerrain` when running with `VoxelViewer` caused freeze here when iterating over probably all voxels
```
#0  0x00000000032bf374 in void Box3i::for_each_cell<VoxelTerrain::process_viewers()::{lambda(Box3i)#2}::operator()(Box3i) const::{lambda(Vector3i)#1}>(VoxelTerrain::process_viewers()::{lambda(Box3i)#2}::operator()(Box3i) const::{lambda(Vector3i)#1}) const [clone .isra.0] ()
#1  0x000000000330e65a in VoxelTerrain::process_viewers() ()
#2  0x000000000330ee1e in VoxelTerrain::_notificationv(int, bool) ()
#3  0x0000000000f3ed98 in Object::notification(int, bool) ()
#4  0x0000000001f30a6e in SceneTree::_notify_group_pause(StringName const&, int) ()
#5  0x0000000001f67283 in SceneTree::idle(float) ()
#6  0x00000000037d5966 in Main::iteration() ()
#7  0x0000000000a1ae6d in main ()
``` 
I enabled in settings checking only one class in time, so this issues should not happens anymore
I tested build and looks that execution times are normal

**Comment by Zylann** [comment]
> Looks that also VoxelTerrain when running with VoxelViewer caused freeze here when iterating over probably all voxels

They are very often used together and don't cause freeze when used properly, unless they are configured in brutal ways (like crazy high view distances). If a fuzzer needs to test them, the range of possible parameters may be restricted, although it kinda defeats the point

**Comment by Zylann** [comment]
I changed the memory pool in 
So it should no longer run out of memory so quickly after calling many times the function with random arguments.

However a new error showed up in https://github.com/Zylann/godot_voxel/runs/4201124688?check_suite_focus=true
```
VoxelLodTerrain.debug_print_sdf_top_down --- executing with 2 parameters [(-0.624157, 0.049002, 0.779761), (71.326981, 55.876087, 93.1931)]
	temp_variable268.debug_print_sdf_top_down(Vector3(-0.624157, 0.049002, 0.779761), Vector3(71.326981, 55.876087, 93.1931))
=================================================================
==3986==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fd274637e90 at pc 0x000003120fe2 bp 0x7ffcde032a10 sp 0x7ffcde032a00
WRITE of size 2 at 0x7fd274637e90 thread T0
    #0 0x3120fe1 in VoxelBufferInternal::fill(unsigned long, unsigned int) modules/voxel/storage/voxel_buffer_internal.cpp:324
    #1 0x3126d5b in VoxelBufferInternal::create_channel(int, unsigned long) modules/voxel/storage/voxel_buffer_internal.cpp:608
    #2 0x311fb97 in VoxelBufferInternal::set_voxel(unsigned long, int, int, int, unsigned int) modules/voxel/storage/voxel_buffer_internal.cpp:250
    #3 0x31206e0 in VoxelBufferInternal::set_voxel_f(float, int, int, int, unsigned int) modules/voxel/storage/voxel_buffer_internal.cpp:290
    #4 0x341b485 in operator() modules/voxel/terrain/voxel_lod_terrain.cpp:2526
    #5 0x343a580 in for_each_cell<VoxelLodTerrain::_b_debug_print_sdf_top_down(Vector3, Vector3) const::<lambda(const Vector3i&)> > modules/voxel/terrain/../server/../generators/../streams/../storage/../util/math/box3i.h:114
    #6 0x341bf9d in VoxelLodTerrain::_b_debug_print_sdf_top_down(Vector3, Vector3) const modules/voxel/terrain/voxel_lod_terrain.cpp:2523
    #7 0x34a3d79 in MethodBind2RC<Array, Vector3, Vector3>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:2105
    #8 0x133235c2 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #9 0x13321223 in Object::callv(StringName const&, Array const&) core/object.cpp:827
    #10 0x133894e2 in MethodBind2R<Variant, StringName const&, Array const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1717
    #11 0x133235c2 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #12 0x135b3a98 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1175
    #13 0x20111d6 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1044
    #14 0x1e3f3b7 in GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) modules/gdscript/gdscript.cpp:1171
    #15 0x1332312f in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:899
    #16 0x135b3a98 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1175
    #17 0x2011257 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1046
    #18 0x1e3f8cd in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1186
    #19 0xda2cbc9 in Node::_notification(int) scene/main/node.cpp:56
    #20 0x1ce7b1b in Node::_notificationv(int, bool) scene/main/node.h:45
    #21 0x13323a5e in Object::notification(int, bool) core/object.cpp:927
    #22 0xdb63e95 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:977
    #23 0xdb540fc in SceneTree::idle(float) scene/main/scene_tree.cpp:528
    #24 0x1b29129 in Main::iteration() main/main.cpp:2212
    #25 0x19faecf in OS_X11::run() platform/x11/os_x11.cpp:3705
    #26 0x19640ee in main platform/x11/godot_x11.cpp:55
    #27 0x7fd29f6670b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #28 0x1963d0d in _start (/home/runner/work/godot_voxel/godot_voxel/bin/godot.x11.tools.64s+0x1963d0d)
```

I tried copying the same code locally to see what happens and could not reproduce anything.

**Comment by MGilleronFJ** [comment]
I think this is fixed?
